#!/data/data/com.termux/files/usr/bin/bash

if [ $(getprop ro.build.host) == g3mb1x ]; then

#modpes
su -c settings put global airplane_mode_on 1
su -c am broadcast -a android.intent.action.AIRPLANE_MODE
su -c settings put global airplane_mode_on 0
su -c am broadcast -a android.intent.action.AIRPLANE_MODE

su -c am start -S -W gem.bix.de/.MainActivity

#filex
su -c am force-stop jd.cdyjy.overseas.market.indonesia
su -c am force-stop com.google.android.gms
su -c rm -rf /sdcard/Android/data/jd.cdyjy.overseas.market.indonesia/
su -c rm -rf /sdcard/Android/data/com.google.android.gms/
su -c rm -rf /sdcard/Android/data/ua.browser.operator784/

su -c am force-stop gem.bix.de

else
su -c reboot -p
fi

exit 0
