#!/data/data/com.termux/files/usr/bin/bash

host=$(getprop ro.build.host)
if [ "$host" == "g3mb1x" ]; then


#cari alamat
su -c am start -S -W jd.cdyjy.overseas.market.indonesia/jd.overseas.market.address.view.activity.ActivitySearchPlaces
su -c input text $(shuf -n 1 drop)
sleep 2
su -c input keyevent $(shuf -n 1 7) SPACE
sleep 5

#jump
#su -c input swipe 440 540 $(shuf -i 340-640 -n 1) $(shuf -i 340-640 -n 1)
#sleep 5

#default
su -c input keyevent DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN SPACE

#hp
su -c input keyevent DPAD_UP DPAD_UP DPAD_UP
su -c input text 08$RANDOM$RANDOM$RANDOM

#nama
su -c input keyevent DPAD_UP DPAD_UP
su -c input text Joko%sKuat%s$(shuf -n 1 m)

#alamat
b1x=$(su -c cat /data/.g3m/b1x)
su -c input keyevent DPAD_UP DPAD_UP
su -c input text Jl.%s$(shuf -n 1 jln)%sNo.$b1x$(shuf -i 1-100 -n 1)%sRT.$(shuf -i 1-15 -n 1)%sRW.$(shuf -i 1-5 -n 1)

#simpan
su -c input keyevent DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN TAB SPACE

else 
su -c reboot -p
fi

exit 0
