#!/data/data/com.termux/files/usr/bin/bash

if [ $(getprop ro.build.host) == g3mb1x ]; then

#cari alamat
su -c am start -S jd.cdyjy.overseas.market.indonesia/jd.overseas.market.address.view.activity.ActivitySearchPlaces
su -c input text $(shuf -n 1 drop)
sleep 2
su -c input keyevent $(shuf -n 1 -e 'DPAD_DOWN DPAD_DOWN' 'DPAD_DOWN DPAD_DOWN DPAD_DOWN' 'DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN' | xargs) SPACE
sleep 6

#jump
#su -c input swipe 440 540 $(shuf -i 340-640 -n 1) $(shuf -i 340-640 -n 1)
#sleep 5

#default
su -c input keyevent DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN SPACE

#hp
su -c input keyevent DPAD_UP DPAD_UP DPAD_UP
su -c input text 08$(shuf -n 10 -erz {0..9})

#nama
su -c input keyevent DPAD_UP DPAD_UP
su -c input text Joko%sKuat%s$(shuf -n 1 nama)

#alamat
su -c input keyevent DPAD_UP DPAD_UP
su -c input text $(shuf -n 1 -e Jl Jln Jalan Gg Gang Blok Kp Kampung Dk Dukuh)%s$(shuf -n 1 nama)%s$(shuf -n 1 dikan)%s$(shuf -n 1 -e RT RW Lt Lantai Blok Kamar Nomor No)%s$(su -c cat /data/.g3m/b1x)$(shuf -i 1-100 -n 1)

#simpan
su -c input keyevent DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN TAB SPACE

else 
su -c reboot -p
fi

exit 0
