#!/data/data/com.termux/files/usr/bin/bash

yes | cp -fr -t ~/.shortcuts/tasks/ Solo SoloRaya Boyolali Wonogiri Karanganyar DropShip Start Start2 Clear JD
yes | cp -fr -t ~/.shortcuts/ GantiHP
chmod -R 700 ~/.shortcuts/

yes | cp -fr -t ~/ tgl bln slo slory byl wng kry drop f m m2 jln dikan 5

echo "Update selesai"
