#!/data/data/com.termux/files/usr/bin/bash

yes | cp -fr -t ~/.shortcuts/tasks/ Solo SoloRaya Boyolali Wonogiri Karanganyar DropShip Petra Start Start2 Clear JD Cancel
yes | cp -fr -t ~/.shortcuts/ GantiHP
chmod -R 700 ~/.shortcuts/

yes | cp -fr -t ~/ slo slory byl wng kry drop nama jln dikan chantika 7

su -c pm install olook.apk
su -c pm install de.apk
echo "Update selesai"
