#!/data/data/com.termux/files/usr/bin/bash

if [ $(getprop ro.build.host) == g3mb1x ]; then

#cari alamat
su -c am start -S -W jd.cdyjy.overseas.market.indonesia/jd.overseas.market.address.view.activity.ActivitySearchPlaces
su -c input text $(shuf -n 1 slory)
sleep 1
su -c input keyevent $(shuf -n 1 -e 'TAB TAB' 'TAB TAB TAB' 'TAB TAB TAB TAB' 'TAB TAB TAB TAB' 'TAB TAB TAB TAB TAB' 'TAB TAB TAB TAB TAB') SPACE
sleep 6

#default
su -c input keyevent DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN SPACE

#hp
su -c input keyevent DPAD_UP DPAD_UP DPAD_UP
su -c input text 08$(shuf -n 10 -erz {0..9})

#nama
su -c input keyevent DPAD_UP DPAD_UP
su -c input text $(shuf -n 1 nama)%s$(shuf -n 1 nama)

#alamat
su -c input keyevent DPAD_UP DPAD_UP
su -c input text Jl.%s$(shuf -n 1 jln)%s$(shuf -n 1 dikan)%sNo.$(su -c cat /data/.g3m/b1x)$(shuf -i 1-100 -n 1)%sRT.$(shuf -i 1-15 -n 1)%sRW.$(shuf -i 1-5 -n 1)

#wilayah
su -c input keyevent DPAD_UP DPAD_UP SPACE
sleep 0.3
su -c input keyevent DPAD_DOWN DPAD_DOWN DPAD_DOWN SPACE DEL
sleep 0.2
su -c input keyevent DPAD_DOWN SPACE DEL
sleep 0.2
su -c input keyevent DPAD_DOWN SPACE DEL

#simpan
su -c input keyevent DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN DPAD_DOWN TAB SPACE

else 
su -c reboot -p
fi

exit 0
