#!/data/data/com.termux/files/usr/bin/bash

if [ $(getprop ro.build.host) == g3mb1x ]; then

#modpes
su -c settings put global airplane_mode_on 1
su -c am broadcast -a android.intent.action.AIRPLANE_MODE
sleep 0.5
su -c settings put global airplane_mode_on 0
su -c am broadcast -a android.intent.action.AIRPLANE_MODE

#start DE
su -c am start -S gem.bix.de/gem.bix.de.MainActivity
sleep 1
su -c input keyevent TAB TAB TAB SPACE TAB SPACE
su -c input keyevent DPAD_RIGHT DPAD_RIGHT SPACE
su -c input keyevent DPAD_LEFT DPAD_LEFT DPAD_LEFT SPACE SPACE SPACE DPAD_RIGHT SPACE

#filex
su -c am force-stop jd.cdyjy.overseas.market.indonesia
su -c am force-stop com.google.android.gms
su -c rm -rf /sdcard/Android/

#OUTLOOK
su -c am start -S ua.browser.operator784/.MainActivity
sleep 8

#username
username=$(shuf -n 1 -erz {A..Z} && shuf -n 1 -erz {A..Z} | shuf -n $(shuf -n 1 -e {7..17}) -erz {A..Z} {a..z} {0..9})
su -c input text $username
echo $username | termux-clipboard-set
su -c input keyevent ENTER
sleep 1

#password
su -c input text nko9mlp0
su -c input keyevent TAB TAB SPACE ENTER
sleep 0.5

#nama
su -c input text $(shuf -n 1 nama)
su -c input keyevent TAB
su -c input text $(shuf -n 1 nama)
su -c input keyevent ENTER
sleep 0.5

#tanggal
su -c input keyevent TAB SPACE
su -c input keyevent $(shuf -n $(shuf -n 1 -e {1..28}) -e TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB | xargs) SPACE

#bln
su -c input keyevent TAB SPACE
su -c input keyevent $(shuf -n $(shuf -n 1 -e {1..28}) -e TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB TAB | xargs) SPACE

#tahun
su -c input keyevent TAB
su -c input text $(shuf -n 1 -i 1970-2005)
su -c input keyevent ENTER

else 
su -c reboot -p
fi

exit 0
